// DeltaForge on Azure - Platform node on Azure Container Apps with a DURABLE,
// non-root /data backed by Premium NFS Azure Files.
//
// Why this shape:
//   - Container Apps gives a Microsoft-managed, browser-trusted TLS cert on the
//     app FQDN (no Caddy, no self-signed).
//   - The platform needs a durable, path-mounted /data (config + git workspace
//     clones that pipelines/schedules execute from). On Container Apps the only
//     POSIX-correct durable mount is NFS Azure Files, which requires a Premium
//     FileStorage account and a VNet-integrated environment.
//   - NFS share roots are root-owned, so a root init container chowns /data to
//     the engine's uid (65532) before the non-root engine starts.
//   - Delta TABLE data still lives in Blob object storage (Standard account),
//     reached via the managed identity; /data is only config + workspaces.
//   - Compute autoscaling is a separate Container Apps app (Phase 2); it is
//     stateless and spills to local ephemeral disk, so it needs none of this.

// ─────────────────────────────── Core ───────────────────────────────────────
@description('Location for all resources.')
param location string = resourceGroup().location

@description('Short prefix for resource names. Lowercase letters and digits.')
@minLength(3)
@maxLength(16)
param namePrefix string = 'deltaforge'

@description('DeltaForge Platform container image.')
param image string

@description('DeltaForge Compute (worker) container image for the in-app compute node sidecar.')
param computeImage string

@description('Shared secret the compute node sidecar registers with (NODE_SECRET). Trust-on-first-use; any strong value.')
@secure()
param computeNodeSecret string

@description('Registry login server (e.g. <acr>.azurecr.io).')
param registryServer string
@description('Registry username.')
param registryUsername string
@description('Registry password / token.')
@secure()
param registryPassword string

@description('Root init image (chowns the NFS /data mount for the non-root engine). Microsoft Container Registry, no Docker Hub rate limit.')
param initImage string = 'mcr.microsoft.com/azurelinux/base/core:3.0'

@description('vCPU for the Platform container (Consumption: 0.25-4).')
param cpuCores string = '2.0'
@description('Memory for the Platform container (e.g. 4Gi). Must pair with cpuCores.')
param memory string = '4Gi'

// ─────────────────────────── Seeded accounts ────────────────────────────────
@description('Seeded admin account email.')
param adminEmail string = 'admin@deltaforge.local'
@description('Seeded engineer account email.')
param engineerEmail string = 'engineer@deltaforge.local'
@description('DeltaForge license key.')
@secure()
param licenseKey string

// Passwords are supplied by the caller (generated by the deploy script with a
// real password algorithm). Bicep has no random_password primitive.
@secure()
param adminPassword string
@secure()
param engineerPassword string
@secure()
param pgAdminPassword string

// ───────────────────────────── PostgreSQL ───────────────────────────────────
param pgAdminUser string = 'dfadmin'
param pgSkuName string = 'Standard_B1ms'
@allowed([ 'Burstable', 'GeneralPurpose', 'MemoryOptimized' ])
param pgTier string = 'Burstable'
param pgStorageGb int = 32
param pgVersion string = '16'

// ───────────────────────────── Storage ──────────────────────────────────────
@description('Premium NFS file share size (GiB) for /data. Premium minimum is 100.')
@minValue(100)
param dataShareGb int = 100

// ───────────────────────────── Mailer (SMTP) ────────────────────────────────
param smtpHost string = ''
param smtpPort int = 587
param smtpUsername string = ''
@secure()
param smtpPassword string = ''
param mailFrom string = ''
param mailFromName string = 'DeltaForge'
param smtpStartTls bool = true

// ─────────────────────────── Derived names ──────────────────────────────────
// Globally-unique (cross-tenant DNS) names derive uniqueness from
// uniqueString(resourceGroup().id), never a human-set tag, so many customers can
// install from the Marketplace into their own subscriptions without colliding.
var suffix = uniqueString(resourceGroup().id)
var pgServerName = toLower('${namePrefix}-pg-${suffix}')
var blobStorageName = toLower(take(replace('${namePrefix}${suffix}', '-', ''), 24))
var nfsStorageName = toLower(take(replace('${namePrefix}nfs${suffix}', '-', ''), 24))
var keyVaultName = toLower(take('${namePrefix}kv${suffix}', 24))
var logWorkspaceName = '${namePrefix}-logs'
var envName = '${namePrefix}-env'
var containerAppName = '${namePrefix}-platform'
var vnetName = '${namePrefix}-vnet'
var subnetName = '${namePrefix}-snet'
var envStorageName = 'data'
var blobContainerName = 'deltatables'
var databaseName = 'deltaforge'
var pgFqdn = '${pgServerName}.postgres.database.azure.com'
var dbUrl = 'postgres://${pgAdminUser}:${pgAdminPassword}@${pgFqdn}:5432/${databaseName}?sslmode=require'
var blobZoneRoot = 'abfss://${blobContainerName}@${blobStorageName}.dfs.${environment().suffixes.storage}'
var smtpConfigured = !empty(smtpHost)
var roleBlobContributor = 'ba92f5b4-2d11-453d-a403-e96b0029c9fe' // Storage Blob Data Contributor
var roleKvSecretsUser = '4633458b-17de-408a-b874-0445c86b69e6'  // Key Vault Secrets User
// Ingress targets the web bridge (3031): SPA + /api proxy = the browser surface.
var ingressPort = 3031
var appFqdn = '${containerAppName}.${env.properties.defaultDomain}'
var publicUrl = 'https://${appFqdn}'
// Cloud compute addressing (direct-dial). Compute nodes live BEHIND the control
// plane's own public FQDN, each on a different port (same domain, one port per
// node). A client asks the control plane for the node list and then dials a node
// DIRECTLY at `https://<cp-fqdn>:<port>`; the node returns the result set
// directly. The control plane is a directory / load balancer, NEVER a proxy in
// the data path. The per-host managed TLS cert covers every port on the FQDN.
//
// `register_node` records each node at the host the control plane discovers as
// its OWN public address (parsed from `DELTA_FORGE_PUBLIC_URL` below) rather than
// the mesh-masked peer IP the worker reports, so no per-node host env is needed.
// Exposing each node's port on the control plane's FQDN is a substrate concern
// (additional external port mappings), handled where the compute nodes are
// provisioned, not in this platform template.

// ───────────────────────────── Networking ───────────────────────────────────
// Container Apps NFS requires a VNet-integrated environment; the subnet is
// delegated to the environment and carries a Storage service endpoint so the
// Premium NFS account can be locked to this VNet.
resource vnet 'Microsoft.Network/virtualNetworks@2025-09-01' = {
  name: vnetName
  location: location
  properties: {
    addressSpace: { addressPrefixes: [ '10.20.0.0/16' ] }
    subnets: [
      {
        name: subnetName
        properties: {
          addressPrefix: '10.20.0.0/23'
          delegations: [
            { name: 'aca', properties: { serviceName: 'Microsoft.App/environments' } }
          ]
          serviceEndpoints: [
            { service: 'Microsoft.Storage' }
          ]
        }
      }
    ]
  }
}

// ───────────────────────────── PostgreSQL ───────────────────────────────────
resource pg 'Microsoft.DBforPostgreSQL/flexibleServers@2025-08-01' = {
  name: pgServerName
  location: location
  sku: { name: pgSkuName, tier: pgTier }
  properties: {
    version: pgVersion
    administratorLogin: pgAdminUser
    administratorLoginPassword: pgAdminPassword
    storage: { storageSizeGB: pgStorageGb }
    network: { publicNetworkAccess: 'Enabled' }
    highAvailability: { mode: 'Disabled' }
    backup: { backupRetentionDays: 7, geoRedundantBackup: 'Disabled' }
  }
}
resource pgFirewallAzure 'Microsoft.DBforPostgreSQL/flexibleServers/firewallRules@2025-08-01' = {
  parent: pg
  name: 'AllowAzureServices'
  properties: { startIpAddress: '0.0.0.0', endIpAddress: '0.0.0.0' }
}
resource pgDatabase 'Microsoft.DBforPostgreSQL/flexibleServers/databases@2025-08-01' = {
  parent: pg
  name: databaseName
  properties: { charset: 'UTF8', collation: 'en_US.utf8' }
}
resource pgExtensions 'Microsoft.DBforPostgreSQL/flexibleServers/configurations@2025-08-01' = {
  parent: pg
  name: 'azure.extensions'
  properties: { value: 'btree_gist', source: 'user-override' }
}

// ───────────────────────── Blob storage (table data) ────────────────────────
resource blobStorage 'Microsoft.Storage/storageAccounts@2026-04-01' = {
  name: blobStorageName
  location: location
  sku: { name: 'Standard_LRS' }
  kind: 'StorageV2'
  properties: { minimumTlsVersion: 'TLS1_2', allowBlobPublicAccess: false }
}
resource blobService 'Microsoft.Storage/storageAccounts/blobServices@2026-04-01' = {
  parent: blobStorage
  name: 'default'
}
resource tablesContainer 'Microsoft.Storage/storageAccounts/blobServices/containers@2026-04-01' = {
  parent: blobService
  name: blobContainerName
  properties: { publicAccess: 'None' }
}

// ───────────────────── Premium NFS storage (/data disk) ──────────────────────
// FileStorage (premium) is required for NFS shares. NFS is not encrypted in
// transit, so secure-transfer is off and the account is locked to the VNet.
resource nfsStorage 'Microsoft.Storage/storageAccounts@2026-04-01' = {
  name: nfsStorageName
  location: location
  sku: { name: 'Premium_LRS' }
  kind: 'FileStorage'
  properties: {
    supportsHttpsTrafficOnly: false
    minimumTlsVersion: 'TLS1_2'
    publicNetworkAccess: 'Enabled'
    networkAcls: {
      defaultAction: 'Deny'
      virtualNetworkRules: [
        { id: '${vnet.id}/subnets/${subnetName}', action: 'Allow' }
      ]
    }
  }
}
resource nfsFileService 'Microsoft.Storage/storageAccounts/fileServices@2026-04-01' = {
  parent: nfsStorage
  name: 'default'
}
resource nfsShare 'Microsoft.Storage/storageAccounts/fileServices/shares@2026-04-01' = {
  parent: nfsFileService
  name: envStorageName
  properties: {
    enabledProtocols: 'NFS'
    rootSquash: 'NoRootSquash'
    shareQuota: dataShareGb
  }
}

// ───────────────────────────── Key Vault ────────────────────────────────────
resource keyVault 'Microsoft.KeyVault/vaults@2026-02-01' = {
  name: keyVaultName
  location: location
  properties: {
    sku: { family: 'A', name: 'standard' }
    tenantId: subscription().tenantId
    enableRbacAuthorization: true
    enableSoftDelete: true
    softDeleteRetentionInDays: 7
  }
}
resource kvPgPassword 'Microsoft.KeyVault/vaults/secrets@2026-02-01' = {
  parent: keyVault
  name: 'postgres-admin-password'
  properties: { value: pgAdminPassword }
}
resource kvAdminPassword 'Microsoft.KeyVault/vaults/secrets@2026-02-01' = {
  parent: keyVault
  name: 'deltaforge-admin-password'
  properties: { value: adminPassword }
}
resource kvEngineerPassword 'Microsoft.KeyVault/vaults/secrets@2026-02-01' = {
  parent: keyVault
  name: 'deltaforge-engineer-password'
  properties: { value: engineerPassword }
}
resource kvLicense 'Microsoft.KeyVault/vaults/secrets@2026-02-01' = {
  parent: keyVault
  name: 'deltaforge-license-key'
  properties: { value: licenseKey }
}

// ─────────────────────── Log Analytics + environment ────────────────────────
resource logWorkspace 'Microsoft.OperationalInsights/workspaces@2026-03-01' = {
  name: logWorkspaceName
  location: location
  properties: { sku: { name: 'PerGB2018' }, retentionInDays: 30 }
}

resource env 'Microsoft.App/managedEnvironments@2026-01-01' = {
  name: envName
  location: location
  properties: {
    appLogsConfiguration: {
      destination: 'log-analytics'
      logAnalyticsConfiguration: {
        customerId: logWorkspace.properties.customerId
        sharedKey: logWorkspace.listKeys().primarySharedKey
      }
    }
    workloadProfiles: [
      { name: 'Consumption', workloadProfileType: 'Consumption' }
    ]
    vnetConfiguration: {
      infrastructureSubnetId: '${vnet.id}/subnets/${subnetName}'
      internal: false
    }
  }
}

// NFS /data mount (durable: config + git workspace clones + engine state).
resource envStorage 'Microsoft.App/managedEnvironments/storages@2026-01-01' = {
  parent: env
  name: envStorageName
  properties: {
    nfsAzureFile: {
      server: '${nfsStorageName}.file.${environment().suffixes.storage}'
      shareName: '/${nfsStorageName}/${envStorageName}'
      accessMode: 'ReadWrite'
    }
  }
  dependsOn: [ nfsShare ]
}

// ───────────────────────────── Container app ────────────────────────────────
resource app 'Microsoft.App/containerApps@2026-01-01' = {
  name: containerAppName
  location: location
  identity: { type: 'SystemAssigned' }
  properties: {
    managedEnvironmentId: env.id
    workloadProfileName: 'Consumption'
    configuration: {
      activeRevisionsMode: 'Single'
      ingress: {
        external: true
        targetPort: ingressPort
        transport: 'auto'
        allowInsecure: false
        traffic: [ { latestRevision: true, weight: 100 } ]
        // Same FQDN, different ports (direct-dial model). The per-host managed
        // TLS cert covers every port on the FQDN, so all are reachable over https:
        //  - 3000 (control-plane API) EXTERNAL: clients (ODBC/ADBC/CLI) reach
        //    auth + `/api/v1/nodes/recommend` at `https://<fqdn>:3000`.
        //  - 8001 (compute node sidecar) EXTERNAL: clients DIRECT-DIAL the node at
        //    `https://<fqdn>:8001` (the control plane is a directory, not a proxy).
        // The browser web console uses the main ingress (3031 → 443).
        additionalPortMappings: [
          { external: true, targetPort: 3000, exposedPort: 3000 }
          { external: true, targetPort: 8001, exposedPort: 8001 }
        ]
      }
      registries: [
        { server: registryServer, username: registryUsername, passwordSecretRef: 'acr-password' }
      ]
      secrets: concat([
        { name: 'acr-password', value: registryPassword }
        { name: 'db-url', value: dbUrl }
        { name: 'license-key', value: licenseKey }
        { name: 'admin-password', value: adminPassword }
        { name: 'engineer-password', value: engineerPassword }
        { name: 'compute-node-secret', value: computeNodeSecret }
      ], smtpConfigured ? [
        { name: 'smtp-password', value: smtpPassword }
      ] : [])
    }
    template: {
      // Root init container: NFS share roots are root-owned, so make /data
      // writable by the non-root engine (uid/gid 65532) before it starts.
      initContainers: [
        {
          name: 'fix-data-perms'
          image: initImage
          command: [ '/bin/sh', '-c', 'chown -R 65532:65532 /data && chmod 0775 /data' ]
          resources: { cpu: json('0.25'), memory: '0.5Gi' }
          volumeMounts: [ { volumeName: 'data', mountPath: '/data' } ]
        }
      ]
      containers: [
        {
          name: 'platform'
          image: image
          resources: { cpu: json(cpuCores), memory: memory }
          env: concat([
            { name: 'DELTA_FORGE_DB_URL', secretRef: 'db-url' }
            { name: 'DELTA_FORGE_LICENSE_KEY', secretRef: 'license-key' }
            { name: 'DELTA_FORGE_ADMIN_PASSWORD', secretRef: 'admin-password' }
            { name: 'DELTA_FORGE_ENGINEER_PASSWORD', secretRef: 'engineer-password' }
            { name: 'DELTA_FORGE_ADMIN_EMAIL', value: adminEmail }
            { name: 'DELTA_FORGE_ENGINEER_EMAIL', value: engineerEmail }
            { name: 'DELTA_FORGE_ACTIVATE_ON_BOOT', value: '1' }
            { name: 'DELTA_FORGE_PUBLIC_URL', value: publicUrl }
            { name: 'AZURE_STORAGE_ACCOUNT_NAME', value: blobStorageName }
          ], smtpConfigured ? [
            { name: 'DELTA_FORGE_MAIL_PROVIDER', value: 'smtp' }
            { name: 'DELTA_FORGE_MAIL_FROM', value: empty(mailFrom) ? smtpUsername : mailFrom }
            { name: 'DELTA_FORGE_MAIL_FROM_NAME', value: mailFromName }
            { name: 'DELTA_FORGE_SMTP_HOST', value: smtpHost }
            { name: 'DELTA_FORGE_SMTP_PORT', value: string(smtpPort) }
            { name: 'DELTA_FORGE_SMTP_USERNAME', value: smtpUsername }
            { name: 'DELTA_FORGE_SMTP_STARTTLS', value: smtpStartTls ? 'true' : 'false' }
            { name: 'DELTA_FORGE_SMTP_PASSWORD', secretRef: 'smtp-password' }
          ] : [])
          volumeMounts: [ { volumeName: 'data', mountPath: '/data' } ]
        }
        // Compute node sidecar: a pure `delta-forge-compute` container in the
        // SAME app (same FQDN) on its own port (8001), exposed externally above.
        // It registers with the co-located control plane over loopback; the
        // control plane records it at `(<fqdn>, 8001)` (the host it discovers as
        // its own, from DELTA_FORGE_PUBLIC_URL), so clients direct-dial
        // `https://<fqdn>:8001`. Spills to local ephemeral disk (no /data mount).
        {
          name: 'compute'
          image: computeImage
          resources: { cpu: json('1.0'), memory: '2Gi' }
          env: [
            { name: 'CONTROL_PLANE_URL', value: 'http://localhost:3000' }
            { name: 'BIND_HOST', value: '0.0.0.0' }
            { name: 'BIND_PORT', value: '8001' }
            { name: 'NODE_ID', value: 'worker::cloud-1' }
            { name: 'DISPLAY_NAME', value: 'cloud-compute-1' }
            { name: 'NODE_SECRET', secretRef: 'compute-node-secret' }
            // The compute image's nonroot user has no real home (--no-create-home,
            // no HOME set), so $HOME=/home/nonroot is unwritable and the worker's
            // per-user data dir (debug-trace file via dirs::data_local_dir) would be
            // discarded. /data is not mounted into this container, so point HOME at
            // the always-writable /tmp; the compute node is stateless scratch.
            { name: 'HOME', value: '/tmp' }
          ]
        }
      ]
      volumes: [
        { name: 'data', storageType: 'NfsAzureFile', storageName: envStorageName }
      ]
      scale: { minReplicas: 1, maxReplicas: 1 }
    }
  }
  dependsOn: [ pgFirewallAzure, pgDatabase, pgExtensions, tablesContainer, envStorage ]
}

// ───────────────────── Managed-identity role grants ─────────────────────────
resource blobRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(blobStorage.id, app.id, roleBlobContributor)
  scope: blobStorage
  properties: {
    principalId: app.identity.principalId
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', roleBlobContributor)
    principalType: 'ServicePrincipal'
  }
}
resource kvRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(keyVault.id, app.id, roleKvSecretsUser)
  scope: keyVault
  properties: {
    principalId: app.identity.principalId
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', roleKvSecretsUser)
    principalType: 'ServicePrincipal'
  }
}

// ───────────────────────────── Outputs ──────────────────────────────────────
output consoleUrl string = publicUrl
output appFqdn string = appFqdn
output postgresFqdn string = pgFqdn
output keyVaultName string = keyVaultName
output blobZoneRoot string = blobZoneRoot
